import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: '开始使用',
      items: [
        'step-1-home',
        'step-2-canvas',
        {
          type: 'category',
          label: '3. 使用模块',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: '3. 使用模块',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'step-3-modules',
            },
          ],
        },
        'step-4-ai-graph',
        'step-5-tags',
        'step-6-timeline',
        'step-7-settings',
      ],
      link: {
        type: 'generated-index',
        title: '使用指南',
      },
    },
    // {
    //   type: 'autogenerated',
    //   dirName: 'tutorial-basics',
    // },
  ],
  
};

export default sidebars;
